Product list view get
wecode-bootcamp-korea/32-2nd-TerraBox-backend pull request #4
Opened 2022-05-12 10:04 UTC by tbhumblestar

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 영화리스트를 반환

2. 유닛테스트 진행

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 유닛테스트의 사용

2022-05-13 07:39 UTC, lordmyshepherd requested changes

2022-05-13 07:39 UTC, lordmyshepherd commented on .gitignore
> +<<<<<<< HEAD
컨플릭트 해결 제대로 안된 부분이 보이네요!

2022-05-13 07:39 UTC, lordmyshepherd commented on .gitignore
>  <<<<<<< HEAD
git push 하시기 전에 반드시 git diff 명령어 치셔서 변경사항을 확인하고 올리는 습관을 갖으셔야 합니다!
그리고 File changed 탭 눌러서 최종적으로 올린 코드에 대한 마지막 점검도 필수 입니다!

꼭 지켜주세요!

2022-05-13 07:39 UTC, lordmyshepherd commented on movies/migrations/0001_initial.py
> +<<<<<<< HEAD
마이그레이션 파일도 마찬가지 입니다.

2022-05-13 07:39 UTC, lordmyshepherd commented on movies/views.py
> +        for movie in Movie.objects.all()]
성능 이슈는 없을까요?

2022-05-13 07:39 UTC, lordmyshepherd commented on reviews/migrations/0001_initial.py
> +<<<<<<< HEAD
여기도 해결이 필요해 보입니다!

2022-05-13 07:39 UTC, lordmyshepherd commented on users/migrations/0001_initial.py
> +<<<<<<< HEAD
여기도요!

2022-05-13 09:28 UTC, tbhumblestar commented on .gitignore
> +<<<<<<< HEAD
확인했습니다

2022-05-13 09:28 UTC, tbhumblestar commented on movies/views.py
> +        for movie in Movie.objects.all()]
앞에 movies = Movie.objects.all()이 필요하지 않을 것 같아 삭제했습니다
혹시 성능적으로 향상시킬 수 있는 방안이 있을까요?

2022-05-13 09:29 UTC, tbhumblestar commented on movies/migrations/0001_initial.py
> +<<<<<<< HEAD
확인했습니다

2022-05-13 09:29 UTC, tbhumblestar commented on reviews/migrations/0001_initial.py
> +<<<<<<< HEAD
확인했습니다

2022-05-13 09:29 UTC, tbhumblestar commented on users/migrations/0001_initial.py
> +<<<<<<< HEAD
확인했습니다!

2022-05-13 09:58 UTC, lordmyshepherd commented on movies/views.py
> +        for movie in Movie.objects.all()]
Djagno ORM 최적화 시간에 언급한 prefetch_related()를 적용해보면 좋을 것 같습니다-!

2022-05-13 09:59 UTC, lordmyshepherd commented on movies/views.py
> +        for movie in Movie.objects.all()]
성능도 직접 측정해보세요!

2022-05-13 10:01 UTC, lordmyshepherd requested changes

2022-05-13 10:01 UTC, lordmyshepherd commented on movies/views.py
> +        for movie in Movie.objects.all()]
여기에 prefetch_related 메소드를 적용해서 성능을 향상시켜주세요-!

2022-05-13 10:01 UTC, lordmyshepherd commented on movies/tests.py
> +            stillcut_url='test_img2')
테스트도 속도가 굉장히 중요합니다.
그렇기 때문에 테스트 과정 중에 테스트 데이터베이스에 데이터를 생성하는 요청 또한 적게 보낼수록 좋겠죠?

bulk_create()를 사용해서 리펙토링해주세요~

2022-05-16 21:01 UTC, tbhumblestar commented on movies/tests.py
> +            stillcut_url='test_img2')
수정했습니다

2022-05-16 21:02 UTC, tbhumblestar commented on movies/views.py
> +        for movie in Movie.objects.all()]
수정했습니다

'stillcut_url':movie.movieimage_set.all().first().stillcut_url

과 같은식으로 할 경우에는 SQL문을 여러번 호출하던데 이유를 알고 싶습니다!

filter를 사용할 경우 여러번 호출하는 것과 동일한 원리일까요?

2022-05-17 00:43 UTC, lordmyshepherd approved these changes
LGTM 👍 
컨플릭트만 해결해주세요~

2022-05-17 07:14 UTC, merged